Experiment with github workflows I/O

diff --git a/.github/workflows/publish-images.yml b/.github/workflows/publish-images.yml
--- a/.github/workflows/publish-images.yml
+++ b/.github/workflows/publish-images.yml
@@ -67,6 +67,18 @@ jobs:
           tags: ${{ secrets.DOCKER_NAMESPACE }}/${{ github.job }}:latest
           push: true
 
+      - name: This is the droid you are looking for!
+        if: always()
+        run: |
+          echo "### Advice to the lovelorn :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "If the last step failed, then click on the gear icon" >> $GITHUB_STEP_SUMMARY
+          echo "and then click 'View raw logs'" >> $GITHUB_STEP_SUMMARY
+
+      - name: Testing! Testing! 1,2,3.
+        run: |
+          echo "check check"
+          echo "yo duude yo wrong" >&2
+
   atomspace-py:
     needs: atomspace
     runs-on: ubuntu-24.04
